#!/usr/bin/env php
<?php

use Fly50w\CLI\Application;

if (file_exists(__DIR__ . "/vendor/autoload.php")) {
    require_once __DIR__ . "/vendor/autoload.php";
} else {
    require_once dirname(__DIR__) . '/autoload.php';
}

$app = new Application();

$app->run($argv);
